### ISSUE TITLE
Blog page doesn't work on Skeleton

### ISSUE THREAD

**Issue by RayHollister** [Drassil/git-wiki-theme#101]
The blog page just loads a blank page no matter how many posts are in the blog. 

http://www.drassil.org/git-wiki-skeleton/blog/ 

![image](https://user-images.githubusercontent.com/369131/234406101-3aaec549-72e6-4702-a7b1-0651691430e6.png)

I thought it was something that I had done on my site, but I just checked the page and it isn't working there either. 

I tried fixing it, but I wasn't able to discover the cause of the issue.

**Comment by RayHollister** [comment]
After looking at some of the closed issues, I'm sure this has to do with the same issues in [81](https://github.com/Drassil/git-wiki-theme/issues/81), [95](https://github.com/Drassil/git-wiki-theme/issues/95) and [99](https://github.com/Drassil/git-wiki-theme/issues/99)

If you don't get a chance before me, I'll take a look later and do a PR.

**Comment by Yehonal** [comment]
This issue has been addressed here: https://github.com/Drassil/git-wiki-skeleton/commit/91b3ecea9b5d9f40e4d42d3125bf45ffad28e8e6 and here: https://github.com/Drassil/git-wiki-skeleton/commit/e695574efc171599e80adac42013383940974a0b

Thanks for reporting it
