### ISSUE TITLE
Add New Post Unknown ISSUE

### ISSUE THREAD

**Issue by sventek-s** [Drassil/git-wiki-theme#102]
**Describe the bug**
Trying to add a new post from the add new post button seems to open a new file in Github that one can't commit.
I think the issue lies in how the target path is defined but I am not 100% sure.

![image](https://github.com/Drassil/git-wiki-theme/assets/70489395/0f47b530-e771-427e-8cef-bda05f323fca)

**To reproduce**
1. Go to Add new post button on the top right corner
2. Click on it
3. Place a test.md on the new file window on github and maybe a test content then try and commit.

![image](https://github.com/Drassil/git-wiki-theme/assets/70489395/32115167-e4aa-4bb5-ba08-50a0f1c45681)

**Comment by sventek-s** [comment]
I haven't changed it on my URL because I don't understand how patches and fixes work due to how you use the sync function. So I will be waiting for your patch

**Comment by Yehonal** [comment]
Hello @sventek-s
Thanks for the report. I had a look at it and apparently they changed something recently since those buttons used to work. I've applied your suggestion and now it seems to work. Please update your wiki to get the latest changes

Thank you
