### ISSUE TITLE
Dark Mode Doesn't Apply to Mobile Header

### ISSUE THREAD

**Issue by Morpheus636** [Drassil/git-wiki-theme#105]
**Describe the bug**
On mobile, enabling dark mode keeps the header in light mode but inverts the color of the logo.

**To reproduce**
1. Go to any page on a mobile device (or with a browser window resized such that the mobile header is visible.
2. Enable dark mode.
3. Observe the color of the mobile header.

**Expected behavior**
The header should have it's colors inverted, but the logo should not.

**Screenshots**
![image](https://github.com/Drassil/git-wiki-theme/assets/68629053/326df253-a012-4a07-a24b-33294e46c7da)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Version: 117.0.1

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Mini
 - OS: iOS 
 - Browser: Safari, Chrome
 - Version: iOS 17.0.1

@ItsTrashPanda and @CRImier have also reproduced the issue.

**Comment by Yehonal** [comment]
It should be fixed in the latest revision. Feel free to reopen it if it doesn't
