### ISSUE TITLE
POSTS not REFLECTING

### ISSUE THREAD

**Issue by sventek-s** [Drassil/git-wiki-theme#106]
**Describe the bug**

So I just added a new post on my wiki and its not reflecting [My Wiki](https://wiki.th3-gr00t.tk/assets/blog/)

Added [wiki](https://github.com/sventek-s/sventeks-nerd-space/commit/8b0cb738e3d729e58837be4fcbfe14232965cb65) on GitHub

I thought the issue was the way I had named the file and renaming it doesn't fix it.

Further digging in I can see we made changes on the `_config.yml` file. Here is the [diff](https://github.com/sventek-s/sventeks-nerd-space/compare/master...Drassil:git-wiki-skeleton:master) and I am not sure can that be the root cause?

**Comment by sventek-s** [comment]
I have fixed it.

**Comment by Yehonal** [comment]
Hi sorry I completely missed it. What wad the solution eventually?

**Comment by sventek-s** [comment]
So I checked your recent [diffs](https://github.com/sventek-s/sventeks-nerd-space/compare/master...Drassil:git-wiki-skeleton:master) and noticed my [blogs config](https://github.com/sventek-s/sventeks-nerd-space/commit/80a35439fa18e48790b1f497b2ed783335735954) scope path wasn't enclosed with two quotes. Weird bug.

But now its not updating the new post here

![image](https://github.com/Drassil/git-wiki-theme/assets/70489395/489dc324-4521-4ccb-a3d4-39a8758d7ba4)

Latest blogs post Windows config not seen above ...

![image](https://github.com/Drassil/git-wiki-theme/assets/70489395/2d2f23db-f3ae-4716-b723-cfb78abf3e72)
