### ISSUE TITLE
docker-compose breaks due to incompatible ruby version

### ISSUE THREAD

**Issue by hyunlee1o** [Drassil/git-wiki-theme#108]
First of all, i know this bug isn't of this repo but the git-wiki-skeleton one didn't have an issue tab.

**Describe the bug**
`docker compose up` doesn't build the git-wiki-skeleton because of incompatible ruby version

```shell
15.03 
21.40 
21.96 Resolving dependencies..........................
124.9 public_suffix-6.0.1 requires ruby version >= 3.0, which is incompatible with the
124.9 current version, ruby 2.7.0p0
------
failed to solve: process "/bin/sh -c bundle install --gemfile=.env-files/Gemfile.gitlab" did not complete successfully: exit code: 5
```

**To reproduce**
1. `git clone https://github.com/Drassil/git-wiki-skeleton.git`
2. `docker compose up`

**Expected behavior**
The thing building

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04

**Comment by Yehonal** [comment]
This should be solved here:

https://github.com/Drassil/git-wiki-theme/commit/699bc603717023c05ed404a787a9729166ff141a

https://github.com/Drassil/git-wiki-skeleton/commit/c60603b5ca8c4807d2e86595c0ea5b6f1cbf0322

Thank you!
