### ISSUE TITLE
Wrong css file used for head styles

### ISSUE THREAD

**Issue by hyunlee1o** [Drassil/git-wiki-theme#109]
**Describe the bug**
git-wiki-style is not loading properly due to haven a bad link or a missing css file.
I am getting this errors:
```
[2024-07-24 19:22:21] ERROR `/infinity/assets/css/git-wiki-style.css' not found.
```
I found this on the git-wiki-theme code 
``` shell
$ rg git-wiki-style.css
_includes/git-wiki/sections/head/styles.html
5:<link rel="stylesheet" href="{{ '/assets/css/git-wiki-style.css?v=' | append: site.github.build_revision | relative_url }}">
```
Inside the assets/css folder there are only two files, none of them is the git-wiki-style.css
```
 $ ls assets/css/
git-wiki-style.scss  github.css
```

**To reproduce**
1. Serve my website

**Expected behavior**
No error on the log

*Desktop (please complete the following information):**
 - OS: Ubuntu 24.04

**Comment by Yehonal** [comment]
Please provide the repository. 

However, the git-wiki-style.css is available in the remote theme, there's no need to have the assets in your folders

**Comment by hyunlee1o** [comment]
Sorry, i tested it locally and haven't uploaded.

**Comment by Yehonal** [comment]
I just tested on a clean skeleton and I cannot reproduce the issue
