### ISSUE TITLE
[FEATURE/AC-Link] - A page on what the client caches.

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [Drassil/git-wiki-theme#112]
### Issue: https://github.com/azerothcore/wiki/issues/863

> Is your feature request related to a problem? Please describe.
> There have been quite a few times where users and contributors have made changes that require the client cache to be cleared. Sometimes the client caches things that users might not expect, and thus don't clear the cache until they come to the Discord asking for support.
> 
> Describe the solution you'd like
> Having a page describing what fields/tables end up in the client's cache would be quite useful.

To add, I think the cache should be clear after X time (a setting probably) and/or when after change happen to that file. Even if it was just a letter change. From all the 3 things I'm reporting today here, I think this one would be the most urgent or necessary of all of them.

**Comment by Yehonal** [comment]
Is it the whole content that is cached or just the layout/css?

Can it be related? 

https://github.com/orgs/community/discussions/49753

but also this:

https://github.com/orgs/community/discussions/11884

maybe it's cloudflare

**Comment by TheSCREWEDSoftware** [comment]
I haven't read the links yet. But i will right after this reply. the page itself seems to get cache, to the point if i do X changse today and i get PR, client may see the old content in the page then come to discord as example asking for help (for something has already been updated/fix)

**Comment by TheSCREWEDSoftware** [comment]
From what i saw in the 2nd link, it seems that cache of github doesn't last too long, which is understanble as is a free platform. So may be cloudflare indeed, if that's what AC uses

**Comment by Yehonal** [comment]
Closing because of this: https://github.com/azerothcore/wiki/issues/863#issuecomment-2466406740
