### ISSUE TITLE
Integrate liquid TOC generation?

### ISSUE THREAD

**Issue by vzickus** [Drassil/git-wiki-theme#57]
Perhaps this would be something to consider? https://github.com/allejo/jekyll-toc

It seems to me that to have a "static" TOC one would currently need to manually set the paths. The "recently updated post TOC" is not particularly helpful for navigation when new posts are included. Would this solve the issue?

**Comment by Yehonal** [comment]
Amazing! I'll give a try

**Comment by Yehonal** [comment]
Could you create a PR about it?
