### ISSUE TITLE
Add way to write sidebar in Markdown

### ISSUE THREAD

**Issue by nekketsuuu** [Drassil/git-wiki-theme#69]
**Is your feature request related to a problem? Please describe.**

Currently, contents in sidebar is written in HTML using [`sidebar.html`](https://github.com/Drassil/git-wiki/blob/e4dee648440da86091b350d12bb407d3a2e24ef6/_includes/drassil/sidebar.html) and [`inc_before_page_list`](https://github.com/Drassil/git-wiki/blob/e4dee648440da86091b350d12bb407d3a2e24ef6/_config.yml#L93). But this feels strange to me because other wiki pages are written in Markdown. I was surprised a little when GitHub shows HTML after pushing the "Edit" link in sidebar of <http://www.drassil.org/git-wiki>.

**Describe the solution you'd like**

Add a way to use `sidebar.md` instead of `sidebar.html`.

**Possibly related?**

jekyll/jekyll#1303

```
{% capture my_include %}{% include a_markdown_file.md %}{% endcapture %}
{{ my_include | markdownify }}
```

Are there any thoughts on this proposal?

**Comment by Yehonal** [comment]
A "sidebar" is not a page but a layout component and should contain HTML code. 
However, if you really need markdown you can put this:

```
{% capture sidebar_content %}{% include sidebar.md %}{% endcapture %}
{{ sidebar_content | markdownify }}
```

in your sidebar.html and create a sidebar.md in same folder
