### ISSUE TITLE
main_page.md.dist is confusing

### ISSUE THREAD

**Issue by nekketsuuu** [Drassil/git-wiki-theme#73]
**Is your feature request related to a problem? Please describe.**

The file `/wiki/main_page.md.dist` can be confusing when creating a new wiki from scratch.

First, if we just copy the master branch of Drassil/git-wiki and build it with Jekyll, the root page `/` shows a HTML page generated by `/README.md` thanks to [jekyll-readme-index](https://github.com/benbalter/jekyll-readme-index).
In order to configure, we can create `/_config.yml` and `/wiki/main_page.md`. Here, if we leave `/wiki/main_page.md.dist` by *copying* it to `/wiki/main_page.md` instead of renaming, the root page `/` is redirected to `/main_page.md` (not `/main_page`) and it is redirected again to an edit page to create `/wiki/main_page.md`. This is because [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from) handles not only a YAML header of `/wiki/main_page.md` but also that of `/wiki/main_page.md.dist`.

This confuses me. We must rename/delete `/wiki/main_page.md.dist` to construct a wiki correctly.

**Describe the solution you'd like**

In order to avoid this, how about renaming `/wiki/main_page.md.dist` to `/wiki/main_page.md` in this repository and writing quick start instructions on `/wiki/main_page.md`? I think it is better that we can construct the very first wiki by just forking the master branch. Also renaming `/_config.yml.dist` seems good if you want. I can send a pull request if needed.

**Describe alternatives you've considered**

Alternatively, write more install instructions or notes on README.md.

**Comment by Yehonal** [comment]
Yes, please rename both main_page and _config file, it can help us also with using git-wiki directly as "remote_theme" https://help.github.com/en/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll#adding-a-theme

Then, we should also update the installation instructions because now, thanks to github, you can install git-wiki in 3 ways:

1) forking
2) using repository template feature
3) using remote_theme (test needed)

**Comment by Yehonal** [comment]
I would also like to move gh-pages branch to another repo, in this way you don't even need to delete that branch

**Comment by Yehonal** [comment]
I'm trying to configure a test repository using remote_theme feature:

https://github.com/Drassil/git-wiki-demo/blob/master/_config.yml

but doesn't work at all, I cannot figure out why since git-wiki repository includes all needed files requested: https://jekyllrb.com/docs/themes/

**Comment by Yehonal** [comment]
I made some progresses :) 

http://www.drassil.org/git-wiki-demo/README

Specifying layout in front matter it works! it's an example of git-wiki theme installed with remote_theme without forking/cloning

**Comment by Yehonal** [comment]
I've restructured the repositories in this way:

https://github.com/Drassil/git-wiki-theme  (this is the repository that you can use with remote_theme or just fork/copy to create your wiki)

https://github.com/Drassil/git-wiki (this is documentation and demo repository, I preferred to keep the old name for it to avoid issues with search engine rankings etc.)

We can close this issue

**Comment by nekketsuuu** [comment]
Thanks for testing the `remote_theme` feature! However, moving Drassil/git-wiki to Drassil/git-wiki-theme and creating new Drassil/git-wiki is possibly a bad idea. It would have been better to leave Drassil/git-wiki and create a new repository, say Drassil/git-wiki-docs, for the old gh-pages branch. If we have cloned Drassil/git-wiki locally, we need to run `git remote set-utl`. Because of the new Drassil/git-wiki, git throws no error when running `git pull` even if not changing the remote url. Also, this renaming broke existing links on GitHub such as Drassil/git-wiki#73. What is done cannot be undone, but please confirm what happens if you overwrite an existing name in the future. Anyway, thanks again for improving the installation!
