### ISSUE TITLE
The "Read All" Link doesn't seem to work

### ISSUE THREAD

**Issue by lucymhdavies** [Drassil/git-wiki-theme#81]
**Describe the bug**
The "Read All" link from the sidebar leads to an empty page

**To reproduce**
Visible in the demo site:
* https://www.drassil.org/git-wiki/blog/
* Read All link, goes to https://www.drassil.org/git-wiki/blog/

**Expected behavior**
A list of all Posts

**Screenshots**
![image](https://user-images.githubusercontent.com/1116529/75101841-0945f580-55db-11ea-85bb-671dcafd60c8.png)

**Comment by Yehonal** [comment]
Thank you for your report

I've fixed it in latest version. Please, update your _config.yml with following 2 changes:

https://github.com/Drassil/git-wiki-theme/commit/ad95f616560f2f02f948d79e1aa26a0a1d8c74d6

https://github.com/Drassil/git-wiki-theme/commit/b8326b1400db850fb4142d569f095a33465aa5c6
