### ISSUE TITLE
Case sensitive links

### ISSUE THREAD

**Issue by Kitzunu** [Drassil/git-wiki-theme#84]
I would like to suggest that we somehow fix so that case sensitivity doesn't matter in URLs for the wiki.

**Comment by Kitzunu** [comment]
@Yehonal some help? o.o :D

**Comment by Kitzunu** [comment]
After I googled some it says it is not possible to have case sensitive thingy thing....

But I stumbled upon https://gist.github.com/sbliven/0ca4dee4e0190a6b3dc7e3d8040cc395 , perhaps that works? o.o

**Comment by Yehonal** [comment]
I've just noticed this issue :O sorry @Kitzunu 

normally URL are natively case sensitive, the fact that in the browser they work whatever the case you use is because the webserver resolve it for you.

However, can you send me an example of the issue itself?

**Comment by Kitzunu** [comment]
Sure, but I read a bit on this, and for what I found it is not possible to fix

**Comment by Kitzunu** [comment]
https://www.azerothcore.org/wiki/Requirements (works)
https://www.azerothcore.org/wiki/requirements (Prompts to make a new file)

**Comment by Yehonal** [comment]
It's not possible unfortunately. but I think should be better to convert them in "lower-case" only
