### ISSUE TITLE
[GENERAL] Doku broken

### ISSUE THREAD

**Issue by Scan-Rec** [Drassil/git-wiki-theme#86]
http://www.drassil.org/git-wiki/customize

![grafik](https://user-images.githubusercontent.com/45966103/96375605-6f364d00-1169-11eb-8e08-c1997f394d25.png)

Example is missing. Please add one, makes it a lot easier.

**Comment by Yehonal** [comment]
Fixed here: https://github.com/Drassil/git-wiki/commit/c5216a9e1e2aef3e7176d1f85665379e6c2a24b9#diff-34e7439d608e5e846d974db7401fc8d2f12b56c11f425dbd4b70c5628eb83f74 

thank you
