### ISSUE TITLE
WikiName as page title

### ISSUE THREAD

**Issue by karino2** [Drassil/git-wiki-theme#92]
I want to make WikiName as page title, that is , show as h1 at top of the page.
I think GitHub wiki or other standard Wiki treat their WIkiName as page title.

Is there some configuration to do it?

**Comment by Yehonal** [comment]
I do not understand this request sorry, what are you trying to achieve?

Can you show an example?

**Comment by karino2** [comment]
If WikiName is Home.md, then I want the html to be
```
<title>Home</title>
...
<body>
<h1>Home</h1>
...
```

I do it manually in following change.

head.html
```
  {% assign pagetitle = page.name | replace: ".md", "" %}
  {% assign title = site.title | append: " - " | append: pagetitle | strip_html %}

  {% include git-wiki/sections/head/meta.html %}

  <title>{{ title }}</title>
```

and in content.html, 
```
<h1>{{ pagetitle }}</h1>
```

https://github.com/karino2/Biochemistry705x/commit/9df9075399b627ae0dd1591048b9e92e20fa0b0b#diff-07dedeab39f9a5c152de1f02a327e087deab04ad12dbb20e57840cd5d13aa66e

I think this is normal wiki behavior (like github wiki) and it would be better accomplish this more formally (if possible).

**Comment by Yehonal** [comment]
Actually on wikipedia the site title is a suffix not a prefix

**Comment by Yehonal** [comment]
However, at the moment our wiki is using the Jekyll SEO plugin which sets the title automatically based on the page

As you can see from our demo: http://www.drassil.org/git-wiki/changelogs.html all the titles are composed by: `page | site.title`

Which is conform to Wikipedia and other wikis.

**Comment by karino2** [comment]
It's OK to close this issue.
But in the link you put, h1 Changelogs is manually written by hand in markdown like

```
# Changelogs
```

What I said is write h1 automatically from WikiName, which is normal behavior for GithubWiki or Wikipedia.
The point is not the order, but I don't want to write h1 every time I create new page.

**Comment by karino2** [comment]
Also, assign title from WikiName is what I want and it was fixed in this changes. Thanks!

https://github.com/Drassil/git-wiki-theme/commit/291a987ee831e6c9889a38a75d0f66f16b1c0283

**Comment by Yehonal** [comment]
The alternative would be to get the name from the filename, which is not
always what you want to display.

All wiki pages should start with a header that identifies the title. The
filename can't contain certain characters that you might want in the title
and generally it is lower case
