### ISSUE TITLE
[GENERAL] Using Git Wiki without github pages

### ISSUE THREAD

**Issue by Uzay-G** [Drassil/git-wiki-theme#93]
I'm thinking of using the awesome work done with github wiki on other platforms, like netlify / netlify cms.

How should I go about doing this to phase out the github pages specific parts?

Thank you for your help.

**Comment by Yehonal** [comment]
It's doable, but the only way I guess it can work would be to upload the artifacts built on github with jeckyll, on netify. 

So for instance you can build your own artifact using the github actions and jekyll (there are also some existing actions on the marketplace: https://github.com/marketplace/actions/jekyll-deploy-gh-pages) and then you send the files to netify. You need a bit of github action knowledge for it, I do not have a detailed guide unfortunately but if you manage to do it, please share your solution
