### ISSUE TITLE
[GENERAL] How to show all the pages?

### ISSUE THREAD

**Issue by chengjun** [Drassil/git-wiki-theme#96]
It seems that it only show a given number of latest posts on the sidebar. How to show all the wiki pages? Thank you for your kindly reply.

**Comment by Yehonal** [comment]
Hi

You can increase the max number of pages to show by changing the `show_wiki_pages_limit` in your config file (just keep in mind that the order of the pages there is based on update time) 

Alternatively, you can create your sidebar.html with all the page links in there with the order you prefer.

**Comment by chengjun** [comment]
thank you for your reply. following your advice, i would like to see whether i can add pagination into it. thank u.

**Comment by chengjun** [comment]
## Solution

- First, I fork the https://github.com/Drassil/git-wiki/.
- Second，I add a folder with the name "blog" and add an index.html file within it.

The content of the index.html is given as follows:

```
---
title: Wiki Pages
layout: git-wiki-default
---

<!-- This loops through the paginated posts -->
{% for post in paginator.posts %}
    <div class="post-item">
        <p class="author">
            <span class="date">{{ post.date | date: "%-d %B %Y"}}</span>
        </p>
        <div class="git-wiki-content">
            {{ post.excerpt }}

            <a href="{{ post.url | relative_url }}">...Read all</a>
        </div>
    </div>
    <hr>
{% endfor %}

<!-- Pagination links -->
<div class="pagination">
  {% if paginator.previous_page %}
    <a href="{{ paginator.previous_page_path | relative_url }}" class="previous">
      Previous
    </a>
  {% else %}
    <span class="previous">Previous</span>
  {% endif %}
  <span class="page_number ">
    Page: {{ paginator.page }} of {{ paginator.total_pages }}
  </span>
  {% if paginator.next_page %}
    <a href="{{ paginator.next_page_path | relative_url }}" class="next">Next</a>
  {% else %}
    <span class="next ">Next</span>
  {% endif %}
</div>
```
