### ISSUE TITLE
[GENERAL] How do I edit the build script?

### ISSUE THREAD

**Issue by cybertheory** [Drassil/git-wiki-theme#98]
Hi, I would like to edit the build script on actions to update the site incrementally. This way the site would rebuild with each change, rather than having to rebuild the whole site with every change. This would help a lot with large wikis as well as popular ones. Changes would go live faster. Thanks.

**Comment by Yehonal** [comment]
This wiki uses jekyll static site generator, that is the official static site tool integrated in github.
You can either decide to use jekyll by running the default github action, or disable that and use your own action with a custom jeckyll build (I do not offer setup support for that though, but you can google how to do that, also github has some documentation on how to use jekyll manually: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll)

However, there's also a jekyll config that you could try 
https://jekyllrb.com/docs/configuration/incremental-regeneration/

but it is not supported by the default github page builder:
https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#configuring-jekyll-in-your-github-pages-site
